#!/bin/sh

### BEGIN INIT INFO
# Provides: daemon
# Required-Start: $local_fs $network $syslog
# Required-Stop: $local_fs $network $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: djyurika
# Description: DJ Yurika discord bot JS ver
### END INIT INFO

NAME="djyurika"
PATH="/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin"
APPDIR="/home/djyurika/js"
APPBIN="/usr/bin/node"
LANG="ko_KR.UTF-8"

. /lib/init/vars.sh
. /lib/lsb/init-functions

start() {
	printf "Starting '$NAME'... "
	start-stop-daemon --start --background --make-pidfile --pidfile /var/run/$NAME.pid --chdir "$APPDIR" --startas /bin/bash -- -c "exec $APPBIN $NAME.js > /home/djyurika/logs/$(date +%Y-%m-%dT%H_%M_%S).log 2>&1" || true
	printf "done\n"
}

killtree() {
	local _pid=$1
	local _sig=${2-TERM}
	for _child in $(ps -o pid --no-headers --ppid ${_pid}); do
		killtree ${_child} ${_sig}
	done
	kill -${_sig} ${_pid}
}

stop() {
	printf "Stopping '$NAME'... "
	[ -z `cat /var/run/$NAME.pid 2>/dev/null` ] || \
	while test -d /proc/$(cat /var/run/$NAME.pid); do
		killtree $(cat /var/run/$NAME.pid) 15
	sleep 0.5
	done
	[ -z `cat /var/run/$NAME.pid 2>/dev/null` ] || rm /var/run/$NAME.pid
	printf "done\n"
}

status() {
	status_of_proc -p /var/run/$NAME.pid "$APPBIN" "$NAME" && exit 0 || exit $?
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		stop
		start
		;;
	status)
		status
		;;
	*)
		echo "Usage: $NAME {start|stop|restart|status}" >&2
		exit 1
		;;
esac

